# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt_master',
            name='port',
            field=models.CharField(default=8000, max_length=15, verbose_name='主控端口'),
        ),
    ]
