# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-06 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0002_auto_20180906_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salt_master',
            options={},
        ),
        migrations.RemoveField(
            model_name='salt_master',
            name='host',
        ),
        migrations.RemoveField(
            model_name='salt_master',
            name='link_stat',
        ),
        migrations.RemoveField(
            model_name='salt_master',
            name='password',
        ),
        migrations.RemoveField(
            model_name='salt_master',
            name='port',
        ),
        migrations.RemoveField(
            model_name='salt_master',
            name='username',
        ),
    ]
