# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-06 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0003_auto_20180906_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salt_master',
            options={'default_permissions': (), 'permissions': ('manage_master', '管理主控')},
        ),
        migrations.AddField(
            model_name='salt_master',
            name='master_host',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='主控地址'),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='master_link_stat',
            field=models.BooleanField(default=False, verbose_name='连接状态'),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='master_port',
            field=models.CharField(default=8000, max_length=15, verbose_name='主控端口'),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='master_pwd',
            field=models.CharField(max_length=30, null=True, verbose_name='主控密码'),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='master_user',
            field=models.CharField(max_length=30, null=True, verbose_name='主控用户名'),
        ),
    ]
