# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-06 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0006_auto_20180906_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salt_master',
            options={'default_permissions': (), 'permissions': ('manage_master', '管理主控')},
        ),
    ]
