# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0009_auto_20180906_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='salt_minion_acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_acc_host', models.CharField(max_length=50, null=True, unique=True, verbose_name='已授权从机地址')),
                ('minion_acc_master', models.CharField(max_length=50, null=True, verbose_name='所属主控')),
                ('minion_acc_stat', models.BooleanField(default=False, verbose_name='已授权从机状态')),
                ('minion_acc_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('manage_minion', '管理从机'), ('list_minion', '查看从机')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='salt_minion_una',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_una_host', models.CharField(max_length=50, null=True, unique=True, verbose_name='未授权从机地址')),
                ('minion_una_time', models.DateTimeField(auto_now_add=True)),
                ('minion_una_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_more.salt_master', to_field='master_host')),
            ],
            options={
                'permissions': (('manage_minion', '管理从机'), ('list_minion', '查看从机')),
                'default_permissions': (),
            },
        ),
    ]
