# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0010_salt_minion_acc_salt_minion_una'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt_minion_acc',
            name='minion_acc_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
