# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-10 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0013_auto_20180909_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt_minion_acc',
            name='minion_acc_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 11, 20, 28, 928316)),
        ),
    ]
