# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_more', '0014_auto_20180910_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt_minion_acc',
            name='minion_acc_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
